# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20171001_0502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patientId',
            new_name='doctor_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_num',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
