# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20171001_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(default=32, max_length=200),
            preserve_default=False,
        ),
    ]
