# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_patient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(default=b'O+', max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.CharField(default=b'sharath@gmail.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default=b'sharath', max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.CharField(default=b'175', max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default=b'sharath', max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_num',
            field=models.CharField(default=b'123', max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.CharField(default=b'50', max_length=200),
        ),
    ]
